# ref - https://medium.com/@gallaghersam95/the-best-terraform-cd-pipeline-with-github-actions-6ecbaa5f3762

name: 'Terraform setup and plan'
description: 'Setup Terraform and creates plan'
inputs:
  terraform_working_directory:
    description: 'Directory that holds Terraform code'
    required: true
  terraform_version: 
    description: 'Terraform Version'
    required: true
    default: 1.7.5
  terraform_cloud_api_token: 
    description: 'Terraform cloud token'
    required: true
  github_token: 
    description: 'GitHub token for auth'
    required: true
  pr_id:
    description: 'Pull request ID'
    required: true
  jamfpro_client_secret:
    description: 'JAMF Pro service client secret used for Terraform actions'
    required: true
  jamfpro_client_id: 
    description: 'JAMF Pro service clientID used for Terraform actions'
    required: true
  jamfpro_instance_name: 
    description: 'JAMF Pro instance name e.g for https://mycompany.jamfcloud.com , use mycompany'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token:  ${{ inputs.terraform_cloud_api_token }}
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    # - id: 'auth'
    #   name: 'Remote Backend Authentication'
    #   uses: 'google-github-actions/auth@v1'
    #   with:
    #     service_account: ${{ inputs.terraform_sa }}
    #     credentials_json: ${{ inputs.google_sa_key }}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_working_directory }}
      shell: bash
      run: |
        terraform init


    - name: Terraform Plan
      id: plan
      working-directory: ${{ inputs.terraform_working_directory }}
      shell: bash
      run: |
        echo 'plan<<EOF' >> $GITHUB_OUTPUT
        terraform plan -no-color -out=tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Save Artifact
      id: save-artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: ${{ inputs.pr_id }}-tf-plan
        path: ${{ inputs.terraform_working_directory }}/tfplan

    - name: Comment Plan
      id: comment-plan
      uses: peter-evans/create-or-update-comment@v4.0.0
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_id }}
        body: |
          Terraform Plan:

          ```
          ${{ steps.plan.outputs.plan }}
          ```

          Plan saved to GH artifacts.