# ref: https://sentenz.github.io/convention/convention/conventional-commits/
name: "01 - terraform speculative plan: sandbox"

on:
  push:
    branches:
      - 'feat-*'
      - 'fix-*'
      - 'docs-*'
      - 'style-*'
      - 'refactor-*'
      - 'test-*'
      - 'chore-*'
      - 'build-*'
      - 'ci-*'
      - 'perf-*'
    paths:
      - '**/*.tf'
      
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to run speculative plan (must start with feat-, fix-, docs-, style-, refactor-, test-, chore-, build-, ci-, or perf-)'
        required: true
        default: 'feat-'

env:
  TF_CLOUD_ORGANIZATION: "deploymenttheory"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "terraform-jamfpro-sandbox"
  CONFIG_DIRECTORY: "workload/terraform/jamfpro"
  PIPELINE_DEBUG: "true"
  # other env vars are set within tfcloud directly for within the tf workspace

permissions:
  contents: write
  id-token: write
  pull-requests: write
  
jobs:
  branch-check:
    if: >
      github.repository != 'hashicorp-education/learn-terraform-github-actions' &&
      (
        github.event_name == 'workflow_dispatch' ||
        startsWith(github.ref, 'refs/heads/feat-') ||
        startsWith(github.ref, 'refs/heads/fix-') ||
        startsWith(github.ref, 'refs/heads/docs-') ||
        startsWith(github.ref, 'refs/heads/style-') ||
        startsWith(github.ref, 'refs/heads/refactor-') ||
        startsWith(github.ref, 'refs/heads/test-') ||
        startsWith(github.ref, 'refs/heads/chore-') ||
        startsWith(github.ref, 'refs/heads/build-') ||
        startsWith(github.ref, 'refs/heads/ci-') ||
        startsWith(github.ref, 'refs/heads/perf-')
      )
    name: "Terraform Speculative Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        
      - name: Validate Branch Name for manual runs
        if: github.event_name == 'workflow_dispatch'
        run: |
          branch="${{ github.event.inputs.branch_name }}"
          if [[ ! "$branch" =~ ^(feat|fix|docs|style|refactor|test|chore|build|ci|perf)- ]]; then
            echo "Error: Branch name must start with 'feat-', 'fix-', 'docs-', 'style-', 'refactor-', 'test-', 'chore-', 'build-', 'ci-', or 'perf-'"
            exit 1
          fi

  terraform-plan:
    needs: branch-check
    uses: ./.github/workflows/terraform-plan.yml
    with:
      tf_cloud_organization: "deploymenttheory"
      tf_workspace: "terraform-jamfpro-sandbox" 
      target_environment: "sandbox"
      debug: ${{ inputs.debug }}
      config_directory: "workload/terraform/jamfpro"
      release_version: release-${{ needs.create-version-and-release.outputs.new_version }}-to-sandbox
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}