name: "03 - terraform apply: staging"

on:
  pull_request:
    types: [closed]
    branches: [staging]

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

permissions:
  contents: read
  id-token: write

jobs:
  terraform-apply:
    uses: ./.github/workflows/terraform-apply.yml
    with:
      tf_cloud_organization: "deploymenttheory"
      tf_workspace: "terraform-jamfpro-staging"
      config_directory: "workload/terraform/jamfpro"
      debug: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  branch-cleanup:
    needs: [terraform-apply]
    uses: ./.github/workflows/branch-cleanup.yml
    with:
      branch_name: ${{ github.event.pull_request.head.ref }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  send-notification:
    needs: [terraform-apply]
    if: always()
    uses: ./.github/workflows/send-notification.yml
    with:
      environment: "Staging"
      result: ${{ needs.terraform-apply.result == 'success' && 'success' || 'failure' }}
      notification_channel: msteams
    secrets: inherit