name: "Versioning and Release"

on:
  workflow_dispatch:
    inputs:
      source_environment:
        description: 'Source environment'
        required: true
        type: choice
        options:
          - sandbox
          - staging
      target_environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - staging
          - production
      debug:
        description: 'Debug mode'
        required: false
        default: 'false'

env:
  TF_CLOUD_ORGANIZATION: "deploymenttheory"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  CONFIG_DIRECTORY: "workload/terraform/jamfpro"

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Validate environment inputs
        run: |
          if [[ "${{ github.event.inputs.source_environment }}" == "sandbox" && "${{ github.event.inputs.target_environment }}" == "production" ]]; then
            echo "Error: Cannot create PR from sandbox to production."
            exit 1
          fi
          if [[ "${{ github.event.inputs.source_environment }}" == "${{ github.event.inputs.target_environment }}" ]]; then
            echo "Error: Source and target environments cannot be the same."
            exit 1
          fi

  create-version-and-release:
    needs: validate-inputs
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.combine_version_hash.outputs.new_version }}
      config_hash: ${{ steps.generate_hash.outputs.config_hash }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.source_environment }}

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.x'

      - name: Determine release version
        id: determine_version
        run: python workload/scripts/version_determinator.py '${{ env.CONFIG_DIRECTORY }}'

      - name: Generate release hash
        id: generate_hash
        run: python workload/scripts/hash_generator.py '${{ env.CONFIG_DIRECTORY }}'

      - name: Combine version and hash
        id: combine_version_hash
        run: |
          NEW_VERSION="${{ steps.determine_version.outputs.version }}-${{ steps.generate_hash.outputs.config_hash }}"
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "CONFIG_HASH=${{ steps.generate_hash.outputs.config_hash }}" >> $GITHUB_ENV

      - name: Display new release version
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          echo "New version: ${{ env.NEW_VERSION }}"

      - name: Create and push new tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: ${{ env.NEW_VERSION }}
          name: Release ${{ env.NEW_VERSION }}
          body: |
            This release was manually triggered by @${{ github.actor }}.
            Source: ${{ github.event.inputs.source_environment }}
            Target: ${{ github.event.inputs.target_environment }}
            Configuration Hash: ${{ env.CONFIG_HASH }}
          draft: false
          prerelease: ${{ github.event.inputs.target_environment != 'production' }}
          files: |
            ${{ env.CONFIG_DIRECTORY }}/**/*.tf
            README.md
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push release branch
        id: create_release_branch
        run: |
          git checkout -b release-${{ env.NEW_VERSION }}
          git push origin release-${{ env.NEW_VERSION }}

  terraform-plan:
    needs: create-version-and-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4.1.7
        with:
          ref: release-${{ needs.create-version-and-release.outputs.new_version }}
          fetch-depth: 0
      
      - name: Set Terraform workspace
        if: ${{ github.event.inputs.debug == 'true' }}
        id: set_workspace
        run: |
          if [[ "${{ github.event.inputs.target_environment }}" == "production" ]]; then
            echo "TF_WORKSPACE=terraform-jamfpro-production" >> $GITHUB_ENV
          else
            echo "TF_WORKSPACE=terraform-jamfpro-staging" >> $GITHUB_ENV
          fi
      
      - name: Verify Terraform Cloud API Token
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          if [ -z "$TF_API_TOKEN" ]; then
            echo "Error: TF_API_TOKEN is not set"
            exit 1
          else
            echo "TF_API_TOKEN is set (value hidden for security)"
          fi
      
      - name: Check Workspace Existence
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          response=$(curl -s \
            --header "Authorization: Bearer $TF_API_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORGANIZATION/workspaces/$TF_WORKSPACE")
          
          if echo $response | grep -q "Not found"; then
            echo "Error: Workspace $TF_WORKSPACE not found in organization $TF_CLOUD_ORGANIZATION"
            exit 1
          else
            echo "Workspace $TF_WORKSPACE exists in organization $TF_CLOUD_ORGANIZATION"
          fi

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.1
        id: plan-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative: true

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.1
        id: plan-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Get Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.3.1
        id: plan-output
        with:
          plan: ${{ fromJSON(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}

      - name: Create PR with Terraform Plan
        uses: actions/github-script@v7.0.1
        id: create-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const additions = parseInt(`${{ steps.plan-output.outputs.add }}`, 10);
            const changes = parseInt(`${{ steps.plan-output.outputs.change }}`, 10);
            const destructions = parseInt(`${{ steps.plan-output.outputs.destroy }}`, 10);

            if (additions === 0 && changes === 0 && destructions === 0) {
              console.log('No changes detected in the Terraform plan. Skipping PR creation.');
              return; // Exit the script without creating a PR
            }

            const planSummary = `
            ## Terraform Cloud Plan Output for ${{ github.event.inputs.target_environment }}

            ### Plan Details:
            - **Plan ID:** ${{ steps.plan-output.outputs.plan_id }}
            - **Additions:** ${{ steps.plan-output.outputs.add }}
            - **Changes:** ${{ steps.plan-output.outputs.change }}
            - **Destructions:** ${{ steps.plan-output.outputs.destroy }}

            ### Summary:
            \`\`\`
            Plan: ${{ steps.plan-output.outputs.add }} to add, ${{ steps.plan-output.outputs.change }} to change, ${{ steps.plan-output.outputs.destroy }} to destroy.
            \`\`\`
            Workspace: ${{ env.TF_WORKSPACE }}
            \`\`\`

            [View Full Terraform Cloud Plan](${{ steps.plan-run.outputs.run_link }})
            `;

            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Terraform Plan for ${{ github.event.inputs.target_environment }} Release ${{ needs.create-version-and-release.outputs.new_version }}`,
              head: `release-${{ needs.create-version-and-release.outputs.new_version }}`,
              base: '${{ github.event.inputs.target_environment }}',
              body: planSummary
            });

            core.setOutput('pull-request-url', pullRequest.html_url);

  send-notification:
    needs: [create-version-and-release, terraform-plan]
    if: always()
    uses: ./.github/workflows/send-notification.yml
    with:
      environment: ${{ github.event.inputs.target_environment }}
      result: ${{ needs.terraform-plan.result == 'success' && 'success' || 'failure' }}
      notification_channel: msteams
      new_version: ${{ needs.create-version-and-release.outputs.new_version }}
    secrets: inherit