name: Apply Terraform Plan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }} # Ensure this is set in your GitHub secrets
      TF_ACTIONS_WORKING_DIR: "workload/terraform/jamfpro" # Adjust this to the directory containing your Terraform configurations
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: latest
        
      - name: Terraform Init with Terraform Cloud Remote Backend
        id: init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform init
        working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
