name: Cleanup Temporary Branch

on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch to be deleted'
        required: true
        type: string

permissions:
  contents: write   # Ensure write permissions to allow branch deletion

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Branch via GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH=${{ inputs.branch }}
          REPO=${{ github.repository }}
          echo "Deleting branch: $BRANCH in repository: $REPO"

          curl -X DELETE \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO/git/refs/heads/$BRANCH
