

- name: Print Environment Variables
  run: |
    echo "Printing all environment variables:"
    env | sort

- name: Verify Terraform Cloud API Token
  run: |
    if [ -z "$TF_API_TOKEN" ]; then
      echo "Error: TF_API_TOKEN is not set"
      exit 1
    else
      echo "TF_API_TOKEN is set (value hidden for security)"
    fi
- name: Check Workspace Existence
  run: |
    response=$(curl -s \
      --header "Authorization: Bearer $TF_API_TOKEN" \
      --header "Content-Type: application/vnd.api+json" \
      "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORGANIZATION/workspaces/$TF_WORKSPACE")
    
    if echo $response | grep -q "Not found"; then
      echo "Error: Workspace $TF_WORKSPACE not found in organization $TF_CLOUD_ORGANIZATION"
      exit 1
    else
      echo "Workspace $TF_WORKSPACE exists in organization $TF_CLOUD_ORGANIZATION"
    fi