name: Check for infrastructure drift

on:
  schedule:
    - cron:  "0 8 * * *"

jobs:
  check_drift:
    runs-on: ubuntu-latest
    name: Check for drift of example terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Check for drift
        uses: dflook/terraform-check@v1.42
        with:
          path: workload/terraform/jamfpro