name: Terraform Plan

on:
  pull_request:

env:
  TERRAFORM_VERSION: "1.7.5"
  TF_IN_AUTOMATION: "True"
  TF_WORKING_DIR: "workload/terraform/jamfpro"
  
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    if: github.event.review.state != 'approved'
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Get PR ID
        id: pr-id
        shell: bash
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
      
      # - name: Get PR ID
      #   id: pr-id-2
      #   shell: bash
      #   run: |
      #     PR_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
      #     "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
      #     | jq '.id')
      #     echo "PR_ID=$PR_ID" >> $GITHUB_OUTPUT
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Terraform Plan
        uses: ./.github/plan
        with:
          terraform_working_directory: ${{ env.TF_WORKING_DIR }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_cloud_api_token: ${{ secrets.TF_API_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
          jamfpro_client_secret: ${{ secrets.JAMFPRO_CLIENT_SECRET }}
          jamfpro_client_id: ${{ secrets.JAMFPRO_CLIENT_ID }}
          jamfpro_instance_name: ${{ secrets.JAMFPRO_INSTANCE_NAME }}
