name: Create terraform plan

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a terraform plan for Jamf Pro
    env:
      JAMFPRO_INSTANCE_NAME: ${{ secrets.JAMFPRO_INSTANCE_NAME }}
      JAMFPRO_CLIENT_ID: ${{ secrets.JAMFPRO_CLIENT_ID }}
      JAMFPRO_CLIENT_SECRET: ${{ secrets.JAMFPRO_CLIENT_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SHARED_DIR: ${{ github.workspace }}/shared
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup shared directory
        run: mkdir -p ${{ env.SHARED_DIR }}

      - name: terraform plan
        uses: deploymenttheory/terraform-github-actions/terraform-plan@v0.0.1
        with:
          path: workload/terraform/jamfpro
          parallelism: 5
          add_github_comment: true 
        
      - name: Upload Terraform Plan as Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: terraform-plan
          path: ${{ env.SHARED_DIR }}/plan.tfplan
  
  
  
      
      - name: Upload Terraform Plan JSON
        uses: actions/upload-artifact@v4.3.1
        with:
          name: terraform-plan-json
          path: ${{ steps.tf_plan.outputs.json_plan_path }}
        if: steps.tf_plan.outputs.json_plan_path != ''
        