name: "Sandbox Versioning"

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  create-sandbox-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Generate hash from Terraform configurations
        run: |
          CONFIG_HASH=$(find workload/terraform/jamfpro -type f -name '*.tf' -exec sha256sum {} + | sha256sum | cut -c1-8)
          echo "CONFIG_HASH=$CONFIG_HASH" >> $GITHUB_ENV

      - name: Get latest sandbox version
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 --match "sandbox-v*" 2>/dev/null || echo "sandbox-v0.0.0")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Increment version and append hash
        run: |
          VERSION=$(echo $LATEST_TAG | sed 's/sandbox-v//')
          IFS='.' read -ra VERSION_PARTS <<< "$VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=$((VERSION_PARTS[2]+1))
          NEW_VERSION="sandbox-v$MAJOR.$MINOR.$PATCH-$CONFIG_HASH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create and push new tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag $NEW_VERSION
          git push origin $NEW_VERSION

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: Sandbox Release ${{ env.NEW_VERSION }}
          body: |
            This is an automated release for the Sandbox environment.
            
            Configuration Hash: ${{ env.CONFIG_HASH }}
          draft: false
          prerelease: false